force

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -37,15 +37,21 @@ jobs:
         run: |
           python train_models.py  # Exécute le fichier d'entraînement
 
-      - name: Add models to Git
+      - name: Commit and Push models
         run: |
           git config --global user.name "GitHub Actions"
           git config --global user.email "actions@github.com"
-          git pull --rebase origin main  # Récupérer les changements récents
+          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+          
+          # Récupérer les changements récents et rebase
+          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, skipping")
+          
           git add models/logistic_regression.pkl models/linear_svc.pkl models/knn.pkl
           git commit -m "Update models via GitHub Actions" || echo "No changes to commit"
-          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
 
+          # Forcer le push si nécessaire
+          git push origin main --force
+          
   deploy-api:
     needs: train-models
     runs-on: ubuntu-latest
